name: ci-wa-labs
on:
  push:
    branches:
      - "develop"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn lint:fix
      - run: yarn build
      - run: yarn test
